export {
  BrainEditor,
  BrainReadOnlyEditor,
  BrainTitle,
  BrainEditorProvider,
  slateToMarkdown,
  getDefaultEditorValue,
  ElementType,
  Mark,
  type EditorProps,
  type TitleProps,
} from "./BrainEditor";

// Re-export all types from the editor package for convenience
export type {
  BrainOSEditor,
  BrainOSElement,
  BrainOSText,
  ParagraphElement,
  HeadingOneElement,
  HeadingTwoElement,
  HeadingThreeElement,
  HeadingFourElement,
  ListItem,
  NumberedList,
  CheckListItem,
  Blockquote,
  ExternalLink,
  NoteLink,
  Tag,
  CodeBlock,
  ThematicBreak,
  BulletedList,
  Image,
  BlockReference,
  Callout,
  Toggle,
  Divider,
} from "@brain/editor";
