/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocRouteImport } from './routes/doc'
import { Route as NewRouteRouteImport } from './routes/_new/route'
import { Route as DevelopersRouteRouteImport } from './routes/_developers/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as DevelopersOauthAppsRouteImport } from './routes/_developers/oauth-apps'
import { Route as DevelopersDevelopersRouteImport } from './routes/_developers/developers'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as NewAppIndexRouteImport } from './routes/_new/app/index'
import { Route as NewAppSettingsRouteImport } from './routes/_new/app/settings'
import { Route as NewAppSearchRouteImport } from './routes/_new/app/search'
import { Route as NewAppDocumentsRouteImport } from './routes/_new/app/documents.'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocRoute = DocRouteImport.update({
  id: '/doc',
  path: '/doc',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRouteRoute = NewRouteRouteImport.update({
  id: '/_new',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRouteRoute = DevelopersRouteRouteImport.update({
  id: '/_developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersOauthAppsRoute = DevelopersOauthAppsRouteImport.update({
  id: '/oauth-apps',
  path: '/oauth-apps',
  getParentRoute: () => DevelopersRouteRoute,
} as any)
const DevelopersDevelopersRoute = DevelopersDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => DevelopersRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const NewAppIndexRoute = NewAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => NewRouteRoute,
} as any)
const NewAppSettingsRoute = NewAppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => NewRouteRoute,
} as any)
const NewAppSearchRoute = NewAppSearchRouteImport.update({
  id: '/app/search',
  path: '/app/search',
  getParentRoute: () => NewRouteRoute,
} as any)
const NewAppDocumentsRoute = NewAppDocumentsRouteImport.update({
  id: '/app/documents/',
  path: '/app/documents/',
  getParentRoute: () => NewRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doc': typeof DocRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/documents': typeof AppDocumentsRoute
  '/developers': typeof DevelopersDevelopersRoute
  '/oauth-apps': typeof DevelopersOauthAppsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/posts': typeof PostsIndexRoute
  '/app/search': typeof NewAppSearchRoute
  '/app/settings': typeof NewAppSettingsRoute
  '/app': typeof NewAppIndexRoute
  '/app/documents': typeof NewAppDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doc': typeof DocRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/documents': typeof AppDocumentsRoute
  '/developers': typeof DevelopersDevelopersRoute
  '/oauth-apps': typeof DevelopersOauthAppsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/posts': typeof PostsIndexRoute
  '/app/search': typeof NewAppSearchRoute
  '/app/settings': typeof NewAppSettingsRoute
  '/app': typeof NewAppIndexRoute
  '/app/documents': typeof NewAppDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_developers': typeof DevelopersRouteRouteWithChildren
  '/_new': typeof NewRouteRouteWithChildren
  '/doc': typeof DocRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_developers/developers': typeof DevelopersDevelopersRoute
  '/_developers/oauth-apps': typeof DevelopersOauthAppsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/posts/': typeof PostsIndexRoute
  '/_new/app/search': typeof NewAppSearchRoute
  '/_new/app/settings': typeof NewAppSettingsRoute
  '/_new/app/': typeof NewAppIndexRoute
  '/_new/app/documents/': typeof NewAppDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doc'
    | '/login'
    | '/newsletter'
    | '/unsubscribe'
    | '/verify'
    | '/documents'
    | '/developers'
    | '/oauth-apps'
    | '/posts/$slug'
    | '/u/$username'
    | '/posts'
    | '/app/search'
    | '/app/settings'
    | '/app'
    | '/app/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doc'
    | '/login'
    | '/newsletter'
    | '/unsubscribe'
    | '/verify'
    | '/documents'
    | '/developers'
    | '/oauth-apps'
    | '/posts/$slug'
    | '/u/$username'
    | '/posts'
    | '/app/search'
    | '/app/settings'
    | '/app'
    | '/app/documents'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_developers'
    | '/_new'
    | '/doc'
    | '/login'
    | '/newsletter'
    | '/unsubscribe'
    | '/verify'
    | '/_app/documents'
    | '/_developers/developers'
    | '/_developers/oauth-apps'
    | '/posts/$slug'
    | '/u/$username'
    | '/posts/'
    | '/_new/app/search'
    | '/_new/app/settings'
    | '/_new/app/'
    | '/_new/app/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DevelopersRouteRoute: typeof DevelopersRouteRouteWithChildren
  NewRouteRoute: typeof NewRouteRouteWithChildren
  DocRoute: typeof DocRoute
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyRoute: typeof VerifyRoute
  PostsSlugRoute: typeof PostsSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc': {
      id: '/doc'
      path: '/doc'
      fullPath: '/doc'
      preLoaderRoute: typeof DocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_new': {
      id: '/_new'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_developers': {
      id: '/_developers'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DevelopersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_developers/oauth-apps': {
      id: '/_developers/oauth-apps'
      path: '/oauth-apps'
      fullPath: '/oauth-apps'
      preLoaderRoute: typeof DevelopersOauthAppsRouteImport
      parentRoute: typeof DevelopersRouteRoute
    }
    '/_developers/developers': {
      id: '/_developers/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersDevelopersRouteImport
      parentRoute: typeof DevelopersRouteRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_new/app/': {
      id: '/_new/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof NewAppIndexRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/_new/app/settings': {
      id: '/_new/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof NewAppSettingsRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/_new/app/search': {
      id: '/_new/app/search'
      path: '/app/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof NewAppSearchRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/_new/app/documents/': {
      id: '/_new/app/documents/'
      path: '/app/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof NewAppDocumentsRouteImport
      parentRoute: typeof NewRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDocumentsRoute: AppDocumentsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DevelopersRouteRouteChildren {
  DevelopersDevelopersRoute: typeof DevelopersDevelopersRoute
  DevelopersOauthAppsRoute: typeof DevelopersOauthAppsRoute
}

const DevelopersRouteRouteChildren: DevelopersRouteRouteChildren = {
  DevelopersDevelopersRoute: DevelopersDevelopersRoute,
  DevelopersOauthAppsRoute: DevelopersOauthAppsRoute,
}

const DevelopersRouteRouteWithChildren = DevelopersRouteRoute._addFileChildren(
  DevelopersRouteRouteChildren,
)

interface NewRouteRouteChildren {
  NewAppSearchRoute: typeof NewAppSearchRoute
  NewAppSettingsRoute: typeof NewAppSettingsRoute
  NewAppIndexRoute: typeof NewAppIndexRoute
  NewAppDocumentsRoute: typeof NewAppDocumentsRoute
}

const NewRouteRouteChildren: NewRouteRouteChildren = {
  NewAppSearchRoute: NewAppSearchRoute,
  NewAppSettingsRoute: NewAppSettingsRoute,
  NewAppIndexRoute: NewAppIndexRoute,
  NewAppDocumentsRoute: NewAppDocumentsRoute,
}

const NewRouteRouteWithChildren = NewRouteRoute._addFileChildren(
  NewRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DevelopersRouteRoute: DevelopersRouteRouteWithChildren,
  NewRouteRoute: NewRouteRouteWithChildren,
  DocRoute: DocRoute,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyRoute: VerifyRoute,
  PostsSlugRoute: PostsSlugRoute,
  UUsernameRoute: UUsernameRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
