/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WriteRouteRouteImport } from './routes/_write/route'
import { Route as NewRouteRouteImport } from './routes/_new/route'
import { Route as DevelopersRouteRouteImport } from './routes/_developers/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as DevelopersOauthAppsRouteImport } from './routes/_developers/oauth-apps'
import { Route as DevelopersDevelopersRouteImport } from './routes/_developers/developers'
import { Route as AppNewsletterSettingsRouteImport } from './routes/_app/newsletter-settings'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as NewAppIndexRouteImport } from './routes/_new/app/index'
import { Route as WriteWriteDocIdRouteImport } from './routes/_write/write.$docId'
import { Route as NewAppSettingsRouteImport } from './routes/_new/app/settings'
import { Route as NewAppSearchRouteImport } from './routes/_new/app/search'
import { Route as NewAppDocumentsRouteImport } from './routes/_new/app/documents.'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRouteRoute = WriteRouteRouteImport.update({
  id: '/_write',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRouteRoute = NewRouteRouteImport.update({
  id: '/_new',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRouteRoute = DevelopersRouteRouteImport.update({
  id: '/_developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersOauthAppsRoute = DevelopersOauthAppsRouteImport.update({
  id: '/oauth-apps',
  path: '/oauth-apps',
  getParentRoute: () => DevelopersRouteRoute,
} as any)
const DevelopersDevelopersRoute = DevelopersDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => DevelopersRouteRoute,
} as any)
const AppNewsletterSettingsRoute = AppNewsletterSettingsRouteImport.update({
  id: '/newsletter-settings',
  path: '/newsletter-settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const NewAppIndexRoute = NewAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => NewRouteRoute,
} as any)
const WriteWriteDocIdRoute = WriteWriteDocIdRouteImport.update({
  id: '/write/$docId',
  path: '/write/$docId',
  getParentRoute: () => WriteRouteRoute,
} as any)
const NewAppSettingsRoute = NewAppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => NewRouteRoute,
} as any)
const NewAppSearchRoute = NewAppSearchRouteImport.update({
  id: '/app/search',
  path: '/app/search',
  getParentRoute: () => NewRouteRoute,
} as any)
const NewAppDocumentsRoute = NewAppDocumentsRouteImport.update({
  id: '/app/documents/',
  path: '/app/documents/',
  getParentRoute: () => NewRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/documents': typeof AppDocumentsRoute
  '/newsletter-settings': typeof AppNewsletterSettingsRoute
  '/developers': typeof DevelopersDevelopersRoute
  '/oauth-apps': typeof DevelopersOauthAppsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts': typeof PostsIndexRoute
  '/app/search': typeof NewAppSearchRoute
  '/app/settings': typeof NewAppSettingsRoute
  '/write/$docId': typeof WriteWriteDocIdRoute
  '/app': typeof NewAppIndexRoute
  '/app/documents': typeof NewAppDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/documents': typeof AppDocumentsRoute
  '/newsletter-settings': typeof AppNewsletterSettingsRoute
  '/developers': typeof DevelopersDevelopersRoute
  '/oauth-apps': typeof DevelopersOauthAppsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts': typeof PostsIndexRoute
  '/app/search': typeof NewAppSearchRoute
  '/app/settings': typeof NewAppSettingsRoute
  '/write/$docId': typeof WriteWriteDocIdRoute
  '/app': typeof NewAppIndexRoute
  '/app/documents': typeof NewAppDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_developers': typeof DevelopersRouteRouteWithChildren
  '/_new': typeof NewRouteRouteWithChildren
  '/_write': typeof WriteRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/newsletter-settings': typeof AppNewsletterSettingsRoute
  '/_developers/developers': typeof DevelopersDevelopersRoute
  '/_developers/oauth-apps': typeof DevelopersOauthAppsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/': typeof PostsIndexRoute
  '/_new/app/search': typeof NewAppSearchRoute
  '/_new/app/settings': typeof NewAppSettingsRoute
  '/_write/write/$docId': typeof WriteWriteDocIdRoute
  '/_new/app/': typeof NewAppIndexRoute
  '/_new/app/documents/': typeof NewAppDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/newsletter'
    | '/unsubscribe'
    | '/verify'
    | '/documents'
    | '/newsletter-settings'
    | '/developers'
    | '/oauth-apps'
    | '/posts/$slug'
    | '/posts'
    | '/app/search'
    | '/app/settings'
    | '/write/$docId'
    | '/app'
    | '/app/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/newsletter'
    | '/unsubscribe'
    | '/verify'
    | '/documents'
    | '/newsletter-settings'
    | '/developers'
    | '/oauth-apps'
    | '/posts/$slug'
    | '/posts'
    | '/app/search'
    | '/app/settings'
    | '/write/$docId'
    | '/app'
    | '/app/documents'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_developers'
    | '/_new'
    | '/_write'
    | '/login'
    | '/newsletter'
    | '/unsubscribe'
    | '/verify'
    | '/_app/documents'
    | '/_app/newsletter-settings'
    | '/_developers/developers'
    | '/_developers/oauth-apps'
    | '/posts/$slug'
    | '/posts/'
    | '/_new/app/search'
    | '/_new/app/settings'
    | '/_write/write/$docId'
    | '/_new/app/'
    | '/_new/app/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DevelopersRouteRoute: typeof DevelopersRouteRouteWithChildren
  NewRouteRoute: typeof NewRouteRouteWithChildren
  WriteRouteRoute: typeof WriteRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyRoute: typeof VerifyRoute
  PostsSlugRoute: typeof PostsSlugRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_write': {
      id: '/_write'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WriteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_new': {
      id: '/_new'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_developers': {
      id: '/_developers'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DevelopersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_developers/oauth-apps': {
      id: '/_developers/oauth-apps'
      path: '/oauth-apps'
      fullPath: '/oauth-apps'
      preLoaderRoute: typeof DevelopersOauthAppsRouteImport
      parentRoute: typeof DevelopersRouteRoute
    }
    '/_developers/developers': {
      id: '/_developers/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersDevelopersRouteImport
      parentRoute: typeof DevelopersRouteRoute
    }
    '/_app/newsletter-settings': {
      id: '/_app/newsletter-settings'
      path: '/newsletter-settings'
      fullPath: '/newsletter-settings'
      preLoaderRoute: typeof AppNewsletterSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_new/app/': {
      id: '/_new/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof NewAppIndexRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/_write/write/$docId': {
      id: '/_write/write/$docId'
      path: '/write/$docId'
      fullPath: '/write/$docId'
      preLoaderRoute: typeof WriteWriteDocIdRouteImport
      parentRoute: typeof WriteRouteRoute
    }
    '/_new/app/settings': {
      id: '/_new/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof NewAppSettingsRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/_new/app/search': {
      id: '/_new/app/search'
      path: '/app/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof NewAppSearchRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/_new/app/documents/': {
      id: '/_new/app/documents/'
      path: '/app/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof NewAppDocumentsRouteImport
      parentRoute: typeof NewRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppNewsletterSettingsRoute: typeof AppNewsletterSettingsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDocumentsRoute: AppDocumentsRoute,
  AppNewsletterSettingsRoute: AppNewsletterSettingsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DevelopersRouteRouteChildren {
  DevelopersDevelopersRoute: typeof DevelopersDevelopersRoute
  DevelopersOauthAppsRoute: typeof DevelopersOauthAppsRoute
}

const DevelopersRouteRouteChildren: DevelopersRouteRouteChildren = {
  DevelopersDevelopersRoute: DevelopersDevelopersRoute,
  DevelopersOauthAppsRoute: DevelopersOauthAppsRoute,
}

const DevelopersRouteRouteWithChildren = DevelopersRouteRoute._addFileChildren(
  DevelopersRouteRouteChildren,
)

interface NewRouteRouteChildren {
  NewAppSearchRoute: typeof NewAppSearchRoute
  NewAppSettingsRoute: typeof NewAppSettingsRoute
  NewAppIndexRoute: typeof NewAppIndexRoute
  NewAppDocumentsRoute: typeof NewAppDocumentsRoute
}

const NewRouteRouteChildren: NewRouteRouteChildren = {
  NewAppSearchRoute: NewAppSearchRoute,
  NewAppSettingsRoute: NewAppSettingsRoute,
  NewAppIndexRoute: NewAppIndexRoute,
  NewAppDocumentsRoute: NewAppDocumentsRoute,
}

const NewRouteRouteWithChildren = NewRouteRoute._addFileChildren(
  NewRouteRouteChildren,
)

interface WriteRouteRouteChildren {
  WriteWriteDocIdRoute: typeof WriteWriteDocIdRoute
}

const WriteRouteRouteChildren: WriteRouteRouteChildren = {
  WriteWriteDocIdRoute: WriteWriteDocIdRoute,
}

const WriteRouteRouteWithChildren = WriteRouteRoute._addFileChildren(
  WriteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DevelopersRouteRoute: DevelopersRouteRouteWithChildren,
  NewRouteRoute: NewRouteRouteWithChildren,
  WriteRouteRoute: WriteRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyRoute: VerifyRoute,
  PostsSlugRoute: PostsSlugRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
