/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as WriteDocIdRouteImport } from './routes/write/$docId'
import { Route as SubscribeConfirmRouteImport } from './routes/subscribe/confirm'
import { Route as AppSubscribersRouteImport } from './routes/app/subscribers'
import { Route as AppSearchRouteImport } from './routes/app/search'
import { Route as AppSettingsRouteRouteImport } from './routes/app/settings/route'
import { Route as UUsernameIndexRouteImport } from './routes/u/$username/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppNewslettersIndexRouteImport } from './routes/app/newsletters/index'
import { Route as UUsernameSlugRouteImport } from './routes/u/$username/$slug'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppSettingsNewsletterRouteImport } from './routes/app/settings/newsletter'
import { Route as AppSettingsAppsRouteImport } from './routes/app/settings/apps'
import { Route as AppSettingsApiKeysRouteImport } from './routes/app/settings/api-keys'
import { Route as AppSettingsAccountRouteImport } from './routes/app/settings/account'
import { Route as AppNewslettersCampaignIdRouteImport } from './routes/app/newsletters/$campaignId'
import { Route as AppDocumentsRouteImport } from './routes/app/documents.'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const WriteDocIdRoute = WriteDocIdRouteImport.update({
  id: '/write/$docId',
  path: '/write/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeConfirmRoute = SubscribeConfirmRouteImport.update({
  id: '/subscribe/confirm',
  path: '/subscribe/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubscribersRoute = AppSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/u/$username/',
  path: '/u/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppNewslettersIndexRoute = AppNewslettersIndexRouteImport.update({
  id: '/newsletters/',
  path: '/newsletters/',
  getParentRoute: () => AppRouteRoute,
} as any)
const UUsernameSlugRoute = UUsernameSlugRouteImport.update({
  id: '/u/$username/$slug',
  path: '/u/$username/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsNewsletterRoute = AppSettingsNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAppsRoute = AppSettingsAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppNewslettersCampaignIdRoute =
  AppNewslettersCampaignIdRouteImport.update({
    id: '/newsletters/$campaignId',
    path: '/newsletters/$campaignId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/search': typeof AppSearchRoute
  '/app/subscribers': typeof AppSubscribersRoute
  '/subscribe/confirm': typeof SubscribeConfirmRoute
  '/write/$docId': typeof WriteDocIdRoute
  '/app/': typeof AppIndexRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/newsletters/$campaignId': typeof AppNewslettersCampaignIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/apps': typeof AppSettingsAppsRoute
  '/app/settings/newsletter': typeof AppSettingsNewsletterRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/u/$username/$slug': typeof UUsernameSlugRoute
  '/app/newsletters': typeof AppNewslettersIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/u/$username': typeof UUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/search': typeof AppSearchRoute
  '/app/subscribers': typeof AppSubscribersRoute
  '/subscribe/confirm': typeof SubscribeConfirmRoute
  '/write/$docId': typeof WriteDocIdRoute
  '/app': typeof AppIndexRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/newsletters/$campaignId': typeof AppNewslettersCampaignIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/apps': typeof AppSettingsAppsRoute
  '/app/settings/newsletter': typeof AppSettingsNewsletterRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/u/$username/$slug': typeof UUsernameSlugRoute
  '/app/newsletters': typeof AppNewslettersIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/u/$username': typeof UUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/search': typeof AppSearchRoute
  '/app/subscribers': typeof AppSubscribersRoute
  '/subscribe/confirm': typeof SubscribeConfirmRoute
  '/write/$docId': typeof WriteDocIdRoute
  '/app/': typeof AppIndexRoute
  '/app/documents/': typeof AppDocumentsRoute
  '/app/newsletters/$campaignId': typeof AppNewslettersCampaignIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/apps': typeof AppSettingsAppsRoute
  '/app/settings/newsletter': typeof AppSettingsNewsletterRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/u/$username/$slug': typeof UUsernameSlugRoute
  '/app/newsletters/': typeof AppNewslettersIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/unsubscribe'
    | '/app/settings'
    | '/app/search'
    | '/app/subscribers'
    | '/subscribe/confirm'
    | '/write/$docId'
    | '/app/'
    | '/app/documents'
    | '/app/newsletters/$campaignId'
    | '/app/settings/account'
    | '/app/settings/api-keys'
    | '/app/settings/apps'
    | '/app/settings/newsletter'
    | '/app/settings/profile'
    | '/u/$username/$slug'
    | '/app/newsletters'
    | '/app/settings/'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unsubscribe'
    | '/app/search'
    | '/app/subscribers'
    | '/subscribe/confirm'
    | '/write/$docId'
    | '/app'
    | '/app/documents'
    | '/app/newsletters/$campaignId'
    | '/app/settings/account'
    | '/app/settings/api-keys'
    | '/app/settings/apps'
    | '/app/settings/newsletter'
    | '/app/settings/profile'
    | '/u/$username/$slug'
    | '/app/newsletters'
    | '/app/settings'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/unsubscribe'
    | '/app/settings'
    | '/app/search'
    | '/app/subscribers'
    | '/subscribe/confirm'
    | '/write/$docId'
    | '/app/'
    | '/app/documents/'
    | '/app/newsletters/$campaignId'
    | '/app/settings/account'
    | '/app/settings/api-keys'
    | '/app/settings/apps'
    | '/app/settings/newsletter'
    | '/app/settings/profile'
    | '/u/$username/$slug'
    | '/app/newsletters/'
    | '/app/settings/'
    | '/u/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  SubscribeConfirmRoute: typeof SubscribeConfirmRoute
  WriteDocIdRoute: typeof WriteDocIdRoute
  UUsernameSlugRoute: typeof UUsernameSlugRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/write/$docId': {
      id: '/write/$docId'
      path: '/write/$docId'
      fullPath: '/write/$docId'
      preLoaderRoute: typeof WriteDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/confirm': {
      id: '/subscribe/confirm'
      path: '/subscribe/confirm'
      fullPath: '/subscribe/confirm'
      preLoaderRoute: typeof SubscribeConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/subscribers': {
      id: '/app/subscribers'
      path: '/subscribers'
      fullPath: '/app/subscribers'
      preLoaderRoute: typeof AppSubscribersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/newsletters/': {
      id: '/app/newsletters/'
      path: '/newsletters'
      fullPath: '/app/newsletters'
      preLoaderRoute: typeof AppNewslettersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/u/$username/$slug': {
      id: '/u/$username/$slug'
      path: '/u/$username/$slug'
      fullPath: '/u/$username/$slug'
      preLoaderRoute: typeof UUsernameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/newsletter': {
      id: '/app/settings/newsletter'
      path: '/newsletter'
      fullPath: '/app/settings/newsletter'
      preLoaderRoute: typeof AppSettingsNewsletterRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/apps': {
      id: '/app/settings/apps'
      path: '/apps'
      fullPath: '/app/settings/apps'
      preLoaderRoute: typeof AppSettingsAppsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/api-keys': {
      id: '/app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/app/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/account': {
      id: '/app/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/newsletters/$campaignId': {
      id: '/app/newsletters/$campaignId'
      path: '/newsletters/$campaignId'
      fullPath: '/app/newsletters/$campaignId'
      preLoaderRoute: typeof AppNewslettersCampaignIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsAppsRoute: typeof AppSettingsAppsRoute
  AppSettingsNewsletterRoute: typeof AppSettingsNewsletterRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsAppsRoute: AppSettingsAppsRoute,
  AppSettingsNewsletterRoute: AppSettingsNewsletterRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppSearchRoute: typeof AppSearchRoute
  AppSubscribersRoute: typeof AppSubscribersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppNewslettersCampaignIdRoute: typeof AppNewslettersCampaignIdRoute
  AppNewslettersIndexRoute: typeof AppNewslettersIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppSearchRoute: AppSearchRoute,
  AppSubscribersRoute: AppSubscribersRoute,
  AppIndexRoute: AppIndexRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppNewslettersCampaignIdRoute: AppNewslettersCampaignIdRoute,
  AppNewslettersIndexRoute: AppNewslettersIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  SubscribeConfirmRoute: SubscribeConfirmRoute,
  WriteDocIdRoute: WriteDocIdRoute,
  UUsernameSlugRoute: UUsernameSlugRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
