/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as editorialEditorialRouteImport } from './routes/(editorial)/_editorial'
import { Route as developersDevelopersRouteImport } from './routes/(developers)/_developers'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as editorialEditorialDocumentsRouteImport } from './routes/(editorial)/_editorial.documents'
import { Route as developersDevelopersKeysRouteImport } from './routes/(developers)/_developers.keys'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth.login'
import { Route as editorialEditorialDocIdRouteImport } from './routes/(editorial)/_editorial.doc.$id'

const editorialRouteImport = createFileRoute('/(editorial)')()
const developersRouteImport = createFileRoute('/(developers)')()
const authRouteImport = createFileRoute('/(auth)')()

const editorialRoute = editorialRouteImport.update({
  id: '/(editorial)',
  getParentRoute: () => rootRouteImport,
} as any)
const developersRoute = developersRouteImport.update({
  id: '/(developers)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const editorialEditorialRoute = editorialEditorialRouteImport.update({
  id: '/_editorial',
  getParentRoute: () => editorialRoute,
} as any)
const developersDevelopersRoute = developersDevelopersRouteImport.update({
  id: '/_developers',
  getParentRoute: () => developersRoute,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => authRoute,
} as any)
const editorialEditorialDocumentsRoute =
  editorialEditorialDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => editorialEditorialRoute,
  } as any)
const developersDevelopersKeysRoute =
  developersDevelopersKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => developersDevelopersRoute,
  } as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)
const editorialEditorialDocIdRoute = editorialEditorialDocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => editorialEditorialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof editorialEditorialRouteWithChildren
  '/newsletter': typeof NewsletterRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/login': typeof authAuthLoginRoute
  '/keys': typeof developersDevelopersKeysRoute
  '/documents': typeof editorialEditorialDocumentsRoute
  '/doc/$id': typeof editorialEditorialDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof editorialEditorialRouteWithChildren
  '/newsletter': typeof NewsletterRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/login': typeof authAuthLoginRoute
  '/keys': typeof developersDevelopersKeysRoute
  '/documents': typeof editorialEditorialDocumentsRoute
  '/doc/$id': typeof editorialEditorialDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/newsletter': typeof NewsletterRoute
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(developers)': typeof developersRouteWithChildren
  '/(developers)/_developers': typeof developersDevelopersRouteWithChildren
  '/(editorial)': typeof editorialRouteWithChildren
  '/(editorial)/_editorial': typeof editorialEditorialRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(developers)/_developers/keys': typeof developersDevelopersKeysRoute
  '/(editorial)/_editorial/documents': typeof editorialEditorialDocumentsRoute
  '/(editorial)/_editorial/doc/$id': typeof editorialEditorialDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/newsletter'
    | '/posts/$postId'
    | '/posts'
    | '/login'
    | '/keys'
    | '/documents'
    | '/doc/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/newsletter'
    | '/posts/$postId'
    | '/posts'
    | '/login'
    | '/keys'
    | '/documents'
    | '/doc/$id'
  id:
    | '__root__'
    | '/'
    | '/newsletter'
    | '/(auth)'
    | '/(auth)/_auth'
    | '/(developers)'
    | '/(developers)/_developers'
    | '/(editorial)'
    | '/(editorial)/_editorial'
    | '/posts/$postId'
    | '/posts/'
    | '/(auth)/_auth/login'
    | '/(developers)/_developers/keys'
    | '/(editorial)/_editorial/documents'
    | '/(editorial)/_editorial/doc/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsletterRoute: typeof NewsletterRoute
  authRoute: typeof authRouteWithChildren
  developersRoute: typeof developersRouteWithChildren
  editorialRoute: typeof editorialRouteWithChildren
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(editorial)': {
      id: '/(editorial)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof editorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(developers)': {
      id: '/(developers)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof developersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(editorial)/_editorial': {
      id: '/(editorial)/_editorial'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof editorialEditorialRouteImport
      parentRoute: typeof editorialRoute
    }
    '/(developers)/_developers': {
      id: '/(developers)/_developers'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof developersDevelopersRouteImport
      parentRoute: typeof developersRoute
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof authRoute
    }
    '/(editorial)/_editorial/documents': {
      id: '/(editorial)/_editorial/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof editorialEditorialDocumentsRouteImport
      parentRoute: typeof editorialEditorialRoute
    }
    '/(developers)/_developers/keys': {
      id: '/(developers)/_developers/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof developersDevelopersKeysRouteImport
      parentRoute: typeof developersDevelopersRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(editorial)/_editorial/doc/$id': {
      id: '/(editorial)/_editorial/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof editorialEditorialDocIdRouteImport
      parentRoute: typeof editorialEditorialRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface authRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

interface developersDevelopersRouteChildren {
  developersDevelopersKeysRoute: typeof developersDevelopersKeysRoute
}

const developersDevelopersRouteChildren: developersDevelopersRouteChildren = {
  developersDevelopersKeysRoute: developersDevelopersKeysRoute,
}

const developersDevelopersRouteWithChildren =
  developersDevelopersRoute._addFileChildren(developersDevelopersRouteChildren)

interface developersRouteChildren {
  developersDevelopersRoute: typeof developersDevelopersRouteWithChildren
}

const developersRouteChildren: developersRouteChildren = {
  developersDevelopersRoute: developersDevelopersRouteWithChildren,
}

const developersRouteWithChildren = developersRoute._addFileChildren(
  developersRouteChildren,
)

interface editorialEditorialRouteChildren {
  editorialEditorialDocumentsRoute: typeof editorialEditorialDocumentsRoute
  editorialEditorialDocIdRoute: typeof editorialEditorialDocIdRoute
}

const editorialEditorialRouteChildren: editorialEditorialRouteChildren = {
  editorialEditorialDocumentsRoute: editorialEditorialDocumentsRoute,
  editorialEditorialDocIdRoute: editorialEditorialDocIdRoute,
}

const editorialEditorialRouteWithChildren =
  editorialEditorialRoute._addFileChildren(editorialEditorialRouteChildren)

interface editorialRouteChildren {
  editorialEditorialRoute: typeof editorialEditorialRouteWithChildren
}

const editorialRouteChildren: editorialRouteChildren = {
  editorialEditorialRoute: editorialEditorialRouteWithChildren,
}

const editorialRouteWithChildren = editorialRoute._addFileChildren(
  editorialRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsletterRoute: NewsletterRoute,
  authRoute: authRouteWithChildren,
  developersRoute: developersRouteWithChildren,
  editorialRoute: editorialRouteWithChildren,
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
