/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevelopersRouteRouteImport } from './routes/_developers/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as DevelopersDevelopersRouteImport } from './routes/_developers/developers'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppEditorDocIdRouteImport } from './routes/_app/editor.$docId'

const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRouteRoute = DevelopersRouteRouteImport.update({
  id: '/_developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersDevelopersRoute = DevelopersDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => DevelopersRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEditorDocIdRoute = AppEditorDocIdRouteImport.update({
  id: '/editor/$docId',
  path: '/editor/$docId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/documents': typeof AppDocumentsRoute
  '/developers': typeof DevelopersDevelopersRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/editor/$docId': typeof AppEditorDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/documents': typeof AppDocumentsRoute
  '/developers': typeof DevelopersDevelopersRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/editor/$docId': typeof AppEditorDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_developers': typeof DevelopersRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_developers/developers': typeof DevelopersDevelopersRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/_app/editor/$docId': typeof AppEditorDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/newsletter'
    | '/documents'
    | '/developers'
    | '/posts/$postId'
    | '/posts'
    | '/editor/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/newsletter'
    | '/documents'
    | '/developers'
    | '/posts/$postId'
    | '/posts'
    | '/editor/$docId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_developers'
    | '/login'
    | '/newsletter'
    | '/_app/documents'
    | '/_developers/developers'
    | '/posts/$postId'
    | '/posts/'
    | '/_app/editor/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DevelopersRouteRoute: typeof DevelopersRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_developers': {
      id: '/_developers'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DevelopersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_developers/developers': {
      id: '/_developers/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersDevelopersRouteImport
      parentRoute: typeof DevelopersRouteRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/editor/$docId': {
      id: '/_app/editor/$docId'
      path: '/editor/$docId'
      fullPath: '/editor/$docId'
      preLoaderRoute: typeof AppEditorDocIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEditorDocIdRoute: typeof AppEditorDocIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDocumentsRoute: AppDocumentsRoute,
  AppEditorDocIdRoute: AppEditorDocIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DevelopersRouteRouteChildren {
  DevelopersDevelopersRoute: typeof DevelopersDevelopersRoute
}

const DevelopersRouteRouteChildren: DevelopersRouteRouteChildren = {
  DevelopersDevelopersRoute: DevelopersDevelopersRoute,
}

const DevelopersRouteRouteWithChildren = DevelopersRouteRoute._addFileChildren(
  DevelopersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DevelopersRouteRoute: DevelopersRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
