name: Deploy web app

on:
  push:
    branches:
      - staging
    paths:
      - apps/web/**
      - packages/**
      - package.json
      - bun.lock

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      # build web app
      - name: Build web application
        working-directory: apps/web
        run: bun run build
        env:
          VITE_PUBLIC_BACKEND_URL: ${{ secrets.VITE_PUBLIC_BACKEND_URL }}
          VITE_PUBLIC_APP_URL: ${{ secrets.VITE_PUBLIC_APP_URL }}

      # deploy web app to cloudflare workers
      - name: Deploy web application
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          packageManager: bun
          workingDirectory: "apps/web"
          wranglerVersion: "4.32.0"

      - name: Print deployment URL
        run: echo "Deployment URL - ${{ steps.deploy.outputs.deployment-url }}"
